---
abstract: 'Replay terminal typescript captures'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.036, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Plugin-Showterm
provides:
  Dancer::Plugin::Showterm:
    file: lib/Dancer/Plugin/Showterm.pm
    version: v0.0.2
requires:
  Dancer: '0'
  Dancer::Plugin: '0'
  File::ShareDir::Tarball: '0'
  Moo: '0'
  MooX::Singleton: '0'
  Path::Tiny: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Dancer-Plugin-Showterm/issues
  homepage: https://github.com/yanick/Dancer-Plugin-Showterm
  repository: https://github.com/yanick/Dancer-Plugin-Showterm.git
version: 0.0.2
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Justin Cook <jscook@users.noreply.github.com>'
